export enum Mask {
  cssunit = 'cssunit',
  url = 'url',
  ip = 'ip',
  email = 'email',
  mac = 'mac',
  vin = 'vin',
  ssn = 'ssn',
  datetime = 'datetime',
  numeric = 'numeric',
  currency = 'currency',
  decimal = 'decimal',
  integer = 'integer',
  percentage = 'percentage',
  indianns = 'indianns',
  jumin = 'jumin',
  juminMask = 'juminMask',
  juminSecure = 'juminSecure',
  foreignerJumin = 'foreignerJumin',
  biz = 'biz',
  bizJumin = 'bizJumin',
  bizJuminMask = 'bizJuminMask',
  bizMask = 'bizMask',
  mngNo = 'mngNo',
  ceoNmMask = 'ceoNmMask',
  pass = 'pass',
  zip = 'zip',
  nameSecure = 'nameSecure',
  addrSecure = 'addrSecure',
  tel = 'tel',
  telSecure = 'telSecure',
  dateShort = 'dateShort',
  dateLong = 'dateLong',
  year = 'year',
  yearMonth = 'yearMonth',
  hourMin = 'hourMin',
  hourMinSec = 'hourMinSec',
  cardNo = 'cardNo',
  cardValidYm = 'cardValidYm',
  FIXED_CODE = 'FIXED_CODE',
  code = 'code',
  number = 'number',
  numberMinus = 'numberMinus',
  numberPoint = 'numberPoint',
  numberPointDigit = 'numberPointDigit',
  numberPointMinus = 'numberPointMinus',
  percent = 'percent',
  percentMinus = 'percentMinus'
}

// export const MaskConst = {
//   cssunit : 'cssunit',
//   url : 'url',
//   ip : 'ip',
//   email : 'email',
//   mac : 'mac',
//   vin : 'vin',
//   ssn : 'ssn',
//   datetime : 'datetime',
//   numeric : 'numeric',
//   currency : 'currency',
//   decimal : 'decimal',
//   integer : 'integer',
//   percentage : 'percentage',
//   indianns : 'indianns',
//   jumin : 'jumin',
//   juminMask : 'juminMask',
//   juminSecure : 'juminSecure',
//   foreignerJumin : 'foreignerJumin',
//   biz : 'biz',
//   bizJumin : 'bizJumin',
//   bizJuminMask : 'bizJuminMask',
//   bizMask : 'bizMask',
//   mngNo : 'mngNo',
//   ceoNmMask : 'ceoNmMask',
//   pass : 'pass',
//   zip : 'zip',
//   nameSecure : 'nameSecure',
//   addrSecure : 'addrSecure',
//   tel : 'tel',
//   telSecure : 'telSecure',
//   dateShort : 'dateShort',
//   dateLong : 'dateLong',
//   year : 'year',
//   yearMonth : 'yearMonth',
//   hourMin : 'hourMin',
//   hourMinSec : 'hourMinSec',
//   cardNo : 'cardNo',
//   cardValidYm : 'cardValidYm',
//   FIXED_CODE : 'FIXED_CODE',
//   num : 'num',
//   num_1 : 'num_1',
//   num_2 : 'num_2',
//   amt : 'amt',
//   percent : 'percent',
//   percent_minus : 'percent_minus'
// }

